import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { Providers } from "@/app/[locale]/providers";
import { ToastContainer } from "react-toastify";
import { GetProgressNavItems } from "@/constants/GetProgressNavConst";

import DictionaryProvider from "./(public)/dictionary-provider";
import { getDictionary } from "./(public)/public-dictionaries";
import ProgressNav from "@/components/navigation/ProgressNav";
import LanguageSwitcher from "@/components/navigation/LanguageSwitcher";
import BackgroundEffects from "@/components/shared/BackgroundEffects";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const dictionary = await getDictionary(locale);
  const navItems = await GetProgressNavItems(locale);
  return (
    <html lang={locale}>
      <body
        className={`relative ${geistSans.variable} ${geistMono.variable} text-black antialiased`}
      >
        <Providers>
          <BackgroundEffects />
          {/* <Navbar navItems={navItems} /> */}
          {/* <div className="absolute left-5 top-5 z-[5]"> */}
          {/* <ThemeSwitcher /> */}
          {/* </div> */}
          <ToastContainer />
          <DictionaryProvider dictionary={dictionary}>
            <ProgressNav navItems={navItems} />
            <LanguageSwitcher />
            {children}
          </DictionaryProvider>
        </Providers>
      </body>
    </html>
  );
}
