import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import ThemeSwitcher from "@/components/shared/ThemeSwitcher";
import { Providers } from "@/app/[locale]/providers";
import { ToastContainer } from "react-toastify";
import { Navbar } from "@/components";
import { GetNavItems } from "@/constants/GetNavbarConst";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const navItems = await GetNavItems(locale);
  return (
    <html lang={locale}>
      <body
        className={`relative ${geistSans.variable} ${geistMono.variable} text-black antialiased dark:text-white`}
      >
        <Providers>
          {/* <Navbar navItems={navItems} /> */}
          <div className="absolute left-5 top-5 z-[5]">
            <ThemeSwitcher />
          </div>
          <ToastContainer />
          <>{children}</>
        </Providers>
      </body>
    </html>
  );
}
